name: Validate and Merge Plugin PR

on:
  pull_request:
    types: [opened, synchronize, reopened]  # 监听 PR 创建、同步和重新打开事件

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Install ClamAV
        run: |
         sudo apt-get update
         sudo apt-get install -y clamav clamav-daemon
         sudo mkdir -p /var/log/clamav
         sudo touch /var/log/clamav/freshclam.log
         sudo chmod 777 /var/log/clamav/freshclam.log

      - name: Validate PR structure
        run: python .github/workflows/validate_pr.py

      - name: Process PR Result
        run: python .github/workflows/handle_pr_result.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
